// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package userprovidermock

import (
	"github.com/asgardeo/thunder/internal/userprovider"
	mock "github.com/stretchr/testify/mock"
)

// NewUserProviderInterfaceMock creates a new instance of UserProviderInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserProviderInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserProviderInterfaceMock {
	mock := &UserProviderInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserProviderInterfaceMock is an autogenerated mock type for the UserProviderInterface type
type UserProviderInterfaceMock struct {
	mock.Mock
}

type UserProviderInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UserProviderInterfaceMock) EXPECT() *UserProviderInterfaceMock_Expecter {
	return &UserProviderInterfaceMock_Expecter{mock: &_m.Mock}
}

// GetUser provides a mock function for the type UserProviderInterfaceMock
func (_mock *UserProviderInterfaceMock) GetUser(userID string) (*userprovider.User, *userprovider.UserProviderError) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *userprovider.User
	var r1 *userprovider.UserProviderError
	if returnFunc, ok := ret.Get(0).(func(string) (*userprovider.User, *userprovider.UserProviderError)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *userprovider.User); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*userprovider.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) *userprovider.UserProviderError); ok {
		r1 = returnFunc(userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*userprovider.UserProviderError)
		}
	}
	return r0, r1
}

// UserProviderInterfaceMock_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type UserProviderInterfaceMock_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - userID string
func (_e *UserProviderInterfaceMock_Expecter) GetUser(userID interface{}) *UserProviderInterfaceMock_GetUser_Call {
	return &UserProviderInterfaceMock_GetUser_Call{Call: _e.mock.On("GetUser", userID)}
}

func (_c *UserProviderInterfaceMock_GetUser_Call) Run(run func(userID string)) *UserProviderInterfaceMock_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserProviderInterfaceMock_GetUser_Call) Return(user *userprovider.User, userProviderError *userprovider.UserProviderError) *UserProviderInterfaceMock_GetUser_Call {
	_c.Call.Return(user, userProviderError)
	return _c
}

func (_c *UserProviderInterfaceMock_GetUser_Call) RunAndReturn(run func(userID string) (*userprovider.User, *userprovider.UserProviderError)) *UserProviderInterfaceMock_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// IdentifyUser provides a mock function for the type UserProviderInterfaceMock
func (_mock *UserProviderInterfaceMock) IdentifyUser(filters map[string]interface{}) (*string, *userprovider.UserProviderError) {
	ret := _mock.Called(filters)

	if len(ret) == 0 {
		panic("no return value specified for IdentifyUser")
	}

	var r0 *string
	var r1 *userprovider.UserProviderError
	if returnFunc, ok := ret.Get(0).(func(map[string]interface{}) (*string, *userprovider.UserProviderError)); ok {
		return returnFunc(filters)
	}
	if returnFunc, ok := ret.Get(0).(func(map[string]interface{}) *string); ok {
		r0 = returnFunc(filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(map[string]interface{}) *userprovider.UserProviderError); ok {
		r1 = returnFunc(filters)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*userprovider.UserProviderError)
		}
	}
	return r0, r1
}

// UserProviderInterfaceMock_IdentifyUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IdentifyUser'
type UserProviderInterfaceMock_IdentifyUser_Call struct {
	*mock.Call
}

// IdentifyUser is a helper method to define mock.On call
//   - filters map[string]interface{}
func (_e *UserProviderInterfaceMock_Expecter) IdentifyUser(filters interface{}) *UserProviderInterfaceMock_IdentifyUser_Call {
	return &UserProviderInterfaceMock_IdentifyUser_Call{Call: _e.mock.On("IdentifyUser", filters)}
}

func (_c *UserProviderInterfaceMock_IdentifyUser_Call) Run(run func(filters map[string]interface{})) *UserProviderInterfaceMock_IdentifyUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]interface{}
		if args[0] != nil {
			arg0 = args[0].(map[string]interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserProviderInterfaceMock_IdentifyUser_Call) Return(s *string, userProviderError *userprovider.UserProviderError) *UserProviderInterfaceMock_IdentifyUser_Call {
	_c.Call.Return(s, userProviderError)
	return _c
}

func (_c *UserProviderInterfaceMock_IdentifyUser_Call) RunAndReturn(run func(filters map[string]interface{}) (*string, *userprovider.UserProviderError)) *UserProviderInterfaceMock_IdentifyUser_Call {
	_c.Call.Return(run)
	return _c
}
