-- Table to store OAuth2 authorization codes.
CREATE TABLE AUTHORIZATION_CODE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    SERVER_ID VARCHAR(255) NOT NULL,
    CODE_ID VARCHAR(36) NOT NULL,
    AUTHORIZATION_CODE VARCHAR(500) NOT NULL,
    CLIENT_ID VARCHAR(255) NOT NULL,
    STATE VARCHAR(50) NOT NULL,
    AUTHZ_DATA TEXT NOT NULL,
    TIME_CREATED DATETIME NOT NULL,
    EXPIRY_TIME DATETIME NOT NULL,
    UNIQUE (CODE_ID, SERVER_ID)
);

-- Index for server isolation on AUTHORIZATION_CODE
CREATE INDEX idx_authorization_code_server_id ON AUTHORIZATION_CODE (SERVER_ID);

-- Table to store flow context metadata and state
CREATE TABLE FLOW_CONTEXT (
    FLOW_ID VARCHAR(36) NOT NULL,
    SERVER_ID VARCHAR(255) NOT NULL,
    APP_ID VARCHAR(36) NOT NULL,
    CURRENT_NODE_ID VARCHAR(50),
    CURRENT_ACTION_ID VARCHAR(50),
    GRAPH_ID VARCHAR(50) NOT NULL,
    RUNTIME_DATA TEXT,
    EXECUTION_HISTORY TEXT,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (FLOW_ID, SERVER_ID)
);

-- Index for server isolation on FLOW_CONTEXT
CREATE INDEX idx_flow_context_server_id ON FLOW_CONTEXT (SERVER_ID);

-- Table to store flow user data
CREATE TABLE FLOW_USER_DATA (
    FLOW_ID VARCHAR(36) NOT NULL,
    SERVER_ID VARCHAR(255) NOT NULL,
    IS_AUTHENTICATED BOOLEAN NOT NULL DEFAULT 0,
    USER_ID VARCHAR(36),
    USER_INPUTS TEXT,
    USER_ATTRIBUTES TEXT,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (FLOW_ID, SERVER_ID),
    FOREIGN KEY (FLOW_ID, SERVER_ID) REFERENCES FLOW_CONTEXT(FLOW_ID, SERVER_ID) ON DELETE CASCADE
);

-- Index for server isolation on FLOW_USER_DATA
CREATE INDEX idx_flow_user_data_server_id ON FLOW_USER_DATA (SERVER_ID);
