// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package consentaudit

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newConsentAuditStoreInterfaceMock creates a new instance of consentAuditStoreInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newConsentAuditStoreInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *consentAuditStoreInterfaceMock {
	mock := &consentAuditStoreInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// consentAuditStoreInterfaceMock is an autogenerated mock type for the consentAuditStoreInterface type
type consentAuditStoreInterfaceMock struct {
	mock.Mock
}

type consentAuditStoreInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *consentAuditStoreInterfaceMock) EXPECT() *consentAuditStoreInterfaceMock_Expecter {
	return &consentAuditStoreInterfaceMock_Expecter{mock: &_m.Mock}
}

// CreateConsentAudit provides a mock function for the type consentAuditStoreInterfaceMock
func (_mock *consentAuditStoreInterfaceMock) CreateConsentAudit(ctx context.Context, rec consentAuditRecord) error {
	ret := _mock.Called(ctx, rec)

	if len(ret) == 0 {
		panic("no return value specified for CreateConsentAudit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, consentAuditRecord) error); ok {
		r0 = returnFunc(ctx, rec)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// consentAuditStoreInterfaceMock_CreateConsentAudit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateConsentAudit'
type consentAuditStoreInterfaceMock_CreateConsentAudit_Call struct {
	*mock.Call
}

// CreateConsentAudit is a helper method to define mock.On call
//   - ctx context.Context
//   - rec consentAuditRecord
func (_e *consentAuditStoreInterfaceMock_Expecter) CreateConsentAudit(ctx interface{}, rec interface{}) *consentAuditStoreInterfaceMock_CreateConsentAudit_Call {
	return &consentAuditStoreInterfaceMock_CreateConsentAudit_Call{Call: _e.mock.On("CreateConsentAudit", ctx, rec)}
}

func (_c *consentAuditStoreInterfaceMock_CreateConsentAudit_Call) Run(run func(ctx context.Context, rec consentAuditRecord)) *consentAuditStoreInterfaceMock_CreateConsentAudit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 consentAuditRecord
		if args[1] != nil {
			arg1 = args[1].(consentAuditRecord)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *consentAuditStoreInterfaceMock_CreateConsentAudit_Call) Return(err error) *consentAuditStoreInterfaceMock_CreateConsentAudit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *consentAuditStoreInterfaceMock_CreateConsentAudit_Call) RunAndReturn(run func(ctx context.Context, rec consentAuditRecord) error) *consentAuditStoreInterfaceMock_CreateConsentAudit_Call {
	_c.Call.Return(run)
	return _c
}
