// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package credentialsmock

import (
	"context"

	"github.com/asgardeo/thunder/internal/authnprovider/common"
	"github.com/asgardeo/thunder/internal/authnprovider/manager"
	"github.com/asgardeo/thunder/internal/system/error/serviceerror"
	mock "github.com/stretchr/testify/mock"
)

// NewCredentialsAuthnServiceInterfaceMock creates a new instance of CredentialsAuthnServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCredentialsAuthnServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CredentialsAuthnServiceInterfaceMock {
	mock := &CredentialsAuthnServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CredentialsAuthnServiceInterfaceMock is an autogenerated mock type for the CredentialsAuthnServiceInterface type
type CredentialsAuthnServiceInterfaceMock struct {
	mock.Mock
}

type CredentialsAuthnServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CredentialsAuthnServiceInterfaceMock) EXPECT() *CredentialsAuthnServiceInterfaceMock_Expecter {
	return &CredentialsAuthnServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type CredentialsAuthnServiceInterfaceMock
func (_mock *CredentialsAuthnServiceInterfaceMock) Authenticate(ctx context.Context, identifiers map[string]interface{}, credentials map[string]interface{}, requestedAttributes *common.RequestedAttributes, metadata *common.AuthnMetadata, authUser manager.AuthUser) (manager.AuthUser, *manager.AuthnBasicResult, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, identifiers, credentials, requestedAttributes, metadata, authUser)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 manager.AuthUser
	var r1 *manager.AuthnBasicResult
	var r2 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]interface{}, map[string]interface{}, *common.RequestedAttributes, *common.AuthnMetadata, manager.AuthUser) (manager.AuthUser, *manager.AuthnBasicResult, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, identifiers, credentials, requestedAttributes, metadata, authUser)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]interface{}, map[string]interface{}, *common.RequestedAttributes, *common.AuthnMetadata, manager.AuthUser) manager.AuthUser); ok {
		r0 = returnFunc(ctx, identifiers, credentials, requestedAttributes, metadata, authUser)
	} else {
		r0 = ret.Get(0).(manager.AuthUser)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]interface{}, map[string]interface{}, *common.RequestedAttributes, *common.AuthnMetadata, manager.AuthUser) *manager.AuthnBasicResult); ok {
		r1 = returnFunc(ctx, identifiers, credentials, requestedAttributes, metadata, authUser)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*manager.AuthnBasicResult)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, map[string]interface{}, map[string]interface{}, *common.RequestedAttributes, *common.AuthnMetadata, manager.AuthUser) *serviceerror.ServiceError); ok {
		r2 = returnFunc(ctx, identifiers, credentials, requestedAttributes, metadata, authUser)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*serviceerror.ServiceError)
		}
	}
	return r0, r1, r2
}

// CredentialsAuthnServiceInterfaceMock_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type CredentialsAuthnServiceInterfaceMock_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - identifiers map[string]interface{}
//   - credentials map[string]interface{}
//   - requestedAttributes *common.RequestedAttributes
//   - metadata *common.AuthnMetadata
//   - authUser manager.AuthUser
func (_e *CredentialsAuthnServiceInterfaceMock_Expecter) Authenticate(ctx interface{}, identifiers interface{}, credentials interface{}, requestedAttributes interface{}, metadata interface{}, authUser interface{}) *CredentialsAuthnServiceInterfaceMock_Authenticate_Call {
	return &CredentialsAuthnServiceInterfaceMock_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, identifiers, credentials, requestedAttributes, metadata, authUser)}
}

func (_c *CredentialsAuthnServiceInterfaceMock_Authenticate_Call) Run(run func(ctx context.Context, identifiers map[string]interface{}, credentials map[string]interface{}, requestedAttributes *common.RequestedAttributes, metadata *common.AuthnMetadata, authUser manager.AuthUser)) *CredentialsAuthnServiceInterfaceMock_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]interface{}
		if args[1] != nil {
			arg1 = args[1].(map[string]interface{})
		}
		var arg2 map[string]interface{}
		if args[2] != nil {
			arg2 = args[2].(map[string]interface{})
		}
		var arg3 *common.RequestedAttributes
		if args[3] != nil {
			arg3 = args[3].(*common.RequestedAttributes)
		}
		var arg4 *common.AuthnMetadata
		if args[4] != nil {
			arg4 = args[4].(*common.AuthnMetadata)
		}
		var arg5 manager.AuthUser
		if args[5] != nil {
			arg5 = args[5].(manager.AuthUser)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *CredentialsAuthnServiceInterfaceMock_Authenticate_Call) Return(authUser1 manager.AuthUser, authnBasicResult *manager.AuthnBasicResult, serviceError *serviceerror.ServiceError) *CredentialsAuthnServiceInterfaceMock_Authenticate_Call {
	_c.Call.Return(authUser1, authnBasicResult, serviceError)
	return _c
}

func (_c *CredentialsAuthnServiceInterfaceMock_Authenticate_Call) RunAndReturn(run func(ctx context.Context, identifiers map[string]interface{}, credentials map[string]interface{}, requestedAttributes *common.RequestedAttributes, metadata *common.AuthnMetadata, authUser manager.AuthUser) (manager.AuthUser, *manager.AuthnBasicResult, *serviceerror.ServiceError)) *CredentialsAuthnServiceInterfaceMock_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttributes provides a mock function for the type CredentialsAuthnServiceInterfaceMock
func (_mock *CredentialsAuthnServiceInterfaceMock) GetAttributes(ctx context.Context, requestedAttributes *common.RequestedAttributes, metadata *common.GetAttributesMetadata, authUser manager.AuthUser) (manager.AuthUser, *common.AttributesResponse, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, requestedAttributes, metadata, authUser)

	if len(ret) == 0 {
		panic("no return value specified for GetAttributes")
	}

	var r0 manager.AuthUser
	var r1 *common.AttributesResponse
	var r2 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, *common.RequestedAttributes, *common.GetAttributesMetadata, manager.AuthUser) (manager.AuthUser, *common.AttributesResponse, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, requestedAttributes, metadata, authUser)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *common.RequestedAttributes, *common.GetAttributesMetadata, manager.AuthUser) manager.AuthUser); ok {
		r0 = returnFunc(ctx, requestedAttributes, metadata, authUser)
	} else {
		r0 = ret.Get(0).(manager.AuthUser)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *common.RequestedAttributes, *common.GetAttributesMetadata, manager.AuthUser) *common.AttributesResponse); ok {
		r1 = returnFunc(ctx, requestedAttributes, metadata, authUser)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.AttributesResponse)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *common.RequestedAttributes, *common.GetAttributesMetadata, manager.AuthUser) *serviceerror.ServiceError); ok {
		r2 = returnFunc(ctx, requestedAttributes, metadata, authUser)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*serviceerror.ServiceError)
		}
	}
	return r0, r1, r2
}

// CredentialsAuthnServiceInterfaceMock_GetAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttributes'
type CredentialsAuthnServiceInterfaceMock_GetAttributes_Call struct {
	*mock.Call
}

// GetAttributes is a helper method to define mock.On call
//   - ctx context.Context
//   - requestedAttributes *common.RequestedAttributes
//   - metadata *common.GetAttributesMetadata
//   - authUser manager.AuthUser
func (_e *CredentialsAuthnServiceInterfaceMock_Expecter) GetAttributes(ctx interface{}, requestedAttributes interface{}, metadata interface{}, authUser interface{}) *CredentialsAuthnServiceInterfaceMock_GetAttributes_Call {
	return &CredentialsAuthnServiceInterfaceMock_GetAttributes_Call{Call: _e.mock.On("GetAttributes", ctx, requestedAttributes, metadata, authUser)}
}

func (_c *CredentialsAuthnServiceInterfaceMock_GetAttributes_Call) Run(run func(ctx context.Context, requestedAttributes *common.RequestedAttributes, metadata *common.GetAttributesMetadata, authUser manager.AuthUser)) *CredentialsAuthnServiceInterfaceMock_GetAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *common.RequestedAttributes
		if args[1] != nil {
			arg1 = args[1].(*common.RequestedAttributes)
		}
		var arg2 *common.GetAttributesMetadata
		if args[2] != nil {
			arg2 = args[2].(*common.GetAttributesMetadata)
		}
		var arg3 manager.AuthUser
		if args[3] != nil {
			arg3 = args[3].(manager.AuthUser)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *CredentialsAuthnServiceInterfaceMock_GetAttributes_Call) Return(authUser1 manager.AuthUser, attributesResponse *common.AttributesResponse, serviceError *serviceerror.ServiceError) *CredentialsAuthnServiceInterfaceMock_GetAttributes_Call {
	_c.Call.Return(authUser1, attributesResponse, serviceError)
	return _c
}

func (_c *CredentialsAuthnServiceInterfaceMock_GetAttributes_Call) RunAndReturn(run func(ctx context.Context, requestedAttributes *common.RequestedAttributes, metadata *common.GetAttributesMetadata, authUser manager.AuthUser) (manager.AuthUser, *common.AttributesResponse, *serviceerror.ServiceError)) *CredentialsAuthnServiceInterfaceMock_GetAttributes_Call {
	_c.Call.Return(run)
	return _c
}
