// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package consent

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewConsentAuditProviderMock creates a new instance of ConsentAuditProviderMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsentAuditProviderMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsentAuditProviderMock {
	mock := &ConsentAuditProviderMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ConsentAuditProviderMock is an autogenerated mock type for the ConsentAuditProvider type
type ConsentAuditProviderMock struct {
	mock.Mock
}

type ConsentAuditProviderMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ConsentAuditProviderMock) EXPECT() *ConsentAuditProviderMock_Expecter {
	return &ConsentAuditProviderMock_Expecter{mock: &_m.Mock}
}

// Record provides a mock function for the type ConsentAuditProviderMock
func (_mock *ConsentAuditProviderMock) Record(ctx context.Context, entry ConsentAuditEntry) error {
	ret := _mock.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for Record")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ConsentAuditEntry) error); ok {
		r0 = returnFunc(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ConsentAuditProviderMock_Record_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Record'
type ConsentAuditProviderMock_Record_Call struct {
	*mock.Call
}

// Record is a helper method to define mock.On call
//   - ctx context.Context
//   - entry ConsentAuditEntry
func (_e *ConsentAuditProviderMock_Expecter) Record(ctx interface{}, entry interface{}) *ConsentAuditProviderMock_Record_Call {
	return &ConsentAuditProviderMock_Record_Call{Call: _e.mock.On("Record", ctx, entry)}
}

func (_c *ConsentAuditProviderMock_Record_Call) Run(run func(ctx context.Context, entry ConsentAuditEntry)) *ConsentAuditProviderMock_Record_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ConsentAuditEntry
		if args[1] != nil {
			arg1 = args[1].(ConsentAuditEntry)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ConsentAuditProviderMock_Record_Call) Return(err error) *ConsentAuditProviderMock_Record_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ConsentAuditProviderMock_Record_Call) RunAndReturn(run func(ctx context.Context, entry ConsentAuditEntry) error) *ConsentAuditProviderMock_Record_Call {
	_c.Call.Return(run)
	return _c
}
