-- Table to store Organization Units
CREATE TABLE ORGANIZATION_UNIT (
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    SERVER_ID   VARCHAR(255) NOT NULL,
    OU_ID       VARCHAR(36) NOT NULL,
    PARENT_ID   VARCHAR(36),
    HANDLE      VARCHAR(100)        NOT NULL,
    NAME        VARCHAR(100)        NOT NULL,
    DESCRIPTION VARCHAR(255),
    CREATED_AT  TEXT DEFAULT (datetime('now')),
    UPDATED_AT  TEXT DEFAULT (datetime('now')),
    UNIQUE (OU_ID, SERVER_ID),
    FOREIGN KEY (PARENT_ID, SERVER_ID) REFERENCES ORGANIZATION_UNIT (OU_ID, SERVER_ID) ON DELETE CASCADE
);

-- Index for server isolation on ORGANIZATION_UNIT
CREATE INDEX idx_organization_unit_server_id ON ORGANIZATION_UNIT (SERVER_ID);

-- Table to store Users
CREATE TABLE USER (
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    SERVER_ID   VARCHAR(255) NOT NULL,
    USER_ID     VARCHAR(36)        NOT NULL,
    OU_ID       VARCHAR(36)        NOT NULL,
    TYPE        TEXT               NOT NULL,
    ATTRIBUTES  TEXT,
    CREDENTIALS TEXT,
    CREATED_AT  TEXT DEFAULT (datetime('now')),
    UPDATED_AT  TEXT DEFAULT (datetime('now')),
    UNIQUE (USER_ID, SERVER_ID)
);

-- Index for server isolation on USER
CREATE INDEX idx_user_server_id ON USER (SERVER_ID);

-- Table to store Groups
CREATE TABLE "GROUP" (
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    SERVER_ID   VARCHAR(255) NOT NULL,
    GROUP_ID    VARCHAR(36)        NOT NULL,
    OU_ID       VARCHAR(36)        NOT NULL,
    NAME        VARCHAR(50)        NOT NULL,
    DESCRIPTION VARCHAR(255),
    CREATED_AT  TEXT DEFAULT (datetime('now')),
    UPDATED_AT  TEXT DEFAULT (datetime('now')),
    UNIQUE (GROUP_ID, SERVER_ID)
);

-- Index for server isolation on GROUP
CREATE INDEX idx_group_server_id ON "GROUP" (SERVER_ID);

-- Table to store Group member assignments
CREATE TABLE GROUP_MEMBER_REFERENCE (
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    SERVER_ID   VARCHAR(255) NOT NULL,
    GROUP_ID    VARCHAR(36) NOT NULL,
    MEMBER_TYPE VARCHAR(7)  NOT NULL,
    MEMBER_ID   VARCHAR(36) NOT NULL,
    CREATED_AT  TEXT DEFAULT (datetime('now')),
    UPDATED_AT  TEXT DEFAULT (datetime('now')),
    FOREIGN KEY (GROUP_ID, SERVER_ID) REFERENCES "GROUP" (GROUP_ID, SERVER_ID) ON DELETE CASCADE
);

-- Index for server isolation on GROUP_MEMBER_REFERENCE
CREATE INDEX idx_group_member_reference_server_id ON GROUP_MEMBER_REFERENCE (SERVER_ID);
